import { useState } from "react";
import { evaluate } from "../services/api";
import DecisionCard from "./DecisionCard";

const ROLES = ["Admin", "Teacher", "Viewer"];
const PLACEHOLDER = `{
  "role": "Admin",
  "tool": "send_email",
  "action": "execute",
  "parameters": {
    "to": "teacher@school.edu",
    "subject": "Homework Reminder",
    "body": "Please submit your assignment before Friday."
  }
}`;
const cap = (s) => s.charAt(0).toUpperCase() + s.slice(1).toLowerCase();

// Turns pasted agent output into the request shape the engine expects. Throws friendly errors.
function parseAgentOutput(text) {
  const clean = text.trim().replace(/^```(?:json)?\s*/i, "").replace(/\s*```$/, "");
  if (!clean) throw new Error("Paste an AI-generated JSON tool call first.");
  let data;
  try { data = JSON.parse(clean); }
  catch (e) { throw new Error(`This isn't valid JSON (${e.message}). Check for missing quotes, commas or brackets.`); }
  if (!data || typeof data !== "object" || Array.isArray(data))
    throw new Error("Expected a single JSON object with role, tool, action and parameters.");
  const missing = ["role", "tool", "action"].filter((k) => typeof data[k] !== "string" || !data[k].trim());
  if (missing.length) throw new Error(`Missing or empty field(s): ${missing.join(", ")}.`);
  const role = cap(data.role.trim());
  if (!ROLES.includes(role)) throw new Error(`Unknown role "${data.role}". Use Admin, Teacher or Viewer.`);
  const params = data.parameters ?? data.params ?? {};
  if (typeof params !== "object" || params === null || Array.isArray(params))
    throw new Error('"parameters" must be a JSON object.');
  return { role, tool: data.tool.trim(), action: cap(data.action.trim()), params };
}

export default function AgentOutput({ onPopulate }) {
  const [text, setText] = useState("");
  const [result, setResult] = useState(null);
  const [error, setError] = useState("");
  const [busy, setBusy] = useState(false);

  async function submit() {
    setError(""); setResult(null);
    let req;
    try { req = parseAgentOutput(text); } catch (e) { return setError(e.message); }
    onPopulate(req);
    setBusy(true);
    try { setResult(await evaluate(req)); }
    catch { setError("Could not reach the guardrail engine. Check that the backend is running on port 8000."); }
    finally { setBusy(false); }
  }

  return (
    <section className="rounded-lg bg-white p-6 shadow-sm">
      <h2 className="text-xl font-semibold text-stone-900">AI Agent Output</h2>
      <p className="mt-1 text-sm text-stone-600">
        Paste a JSON tool call generated by an AI agent. It runs through the same guardrail engine as the manual form below.
      </p>
      <div className="mt-4 grid gap-6 md:grid-cols-2">
        <div className="space-y-3">
          <textarea rows={12} value={text} onChange={(e) => setText(e.target.value)} placeholder={PLACEHOLDER}
            className="w-full rounded border border-stone-300 bg-white px-3 py-2 font-mono text-sm" />
          {error && <p className="text-sm text-rose-700">{error}</p>}
          <button onClick={submit} disabled={busy}
            className="rounded bg-stone-900 px-4 py-2 text-white hover:bg-stone-700 disabled:opacity-50">
            {busy ? "Validating..." : "Validate AI Output"}
          </button>
        </div>
        <div>
          {result ? <DecisionCard r={result} /> : (
            <p className="text-stone-500">The decision, rule and reliability score will appear here.</p>
          )}
        </div>
      </div>
    </section>
  );
}
